r"""Converter: raw comma paths (DB dump) -> hierarchical question config.

No heavy dependencies (no torch/laya import) so CLI tools can use it directly.
"""

INSTR_BY_DEPTH = [
    "Apa maksud utama pelanggan dalam percakapan `body`?",
    "Aspek layanan mana yang paling relevan dengan `body`?",
    "Sub-kategori apa yang paling spesifik menggambarkan `body`?",
]


def parse_paths(data):
    """Accept list of comma path strings, {'paths': [...]}, or level_N dicts.

    Returns list of segment lists, all the same depth (>= 2).
    """
    if isinstance(data, dict):
        data = data.get("paths")
    if not isinstance(data, list) or not data:
        raise ValueError(
            "data path harus list tidak kosong "
            "(string 'L1, L2, ...' atau object level_1..level_N)"
        )
    segs = []
    for item in data:
        if isinstance(item, str):
            parts = [p.strip() for p in item.split(",")]
        elif isinstance(item, dict):
            keys = [k for k in item if isinstance(k, str) and k.startswith("level_")]
            keys.sort(key=lambda k: int(k.split("_")[1]))
            parts = [str(item[k]).strip() for k in keys]
        else:
            raise ValueError(f"path tidak valid: {item!r}")
        if len(parts) < 2 or any(not p for p in parts):
            raise ValueError(f"path harus >= 2 level dan tidak kosong: {item!r}")
        segs.append(parts)
    depth = len(segs[0])
    if any(len(s) != depth for s in segs):
        raise ValueError("semua path harus punya jumlah level sama")
    return segs


def hier_config_from_paths(segs):
    """Comma path segments -> hierarchical config dict.

    Options per level = unique values at that depth (flattened). Descriptions
    for non-leaf levels are generated by joining the option's child values —
    better than null, still worth hand-editing for best accuracy.
    """
    depth = len(segs[0])
    flat = [dict() for _ in range(depth)]  # flat[d][value] -> ordered children

    def add(parts):
        for d in range(depth - 1):
            parent, child = parts[d], parts[d + 1]
            kids = flat[d].setdefault(parent, [])
            if child not in kids:
                kids.append(child)

    for parts in segs:
        add(parts)

    def options_at(d):
        out = []
        for kids in flat[d].values():
            for v in kids:
                if v not in out:
                    out.append(v)
        return out

    levels = {}
    for d in range(depth - 1):
        qid = f"level_{d + 1}"
        crit = {}
        for opt in flat[d].keys():
            kids = flat[d].get(opt, [])
            crit[opt] = ", ".join(kids[:10]) if kids else None
        instr = (
            INSTR_BY_DEPTH[d]
            if d < len(INSTR_BY_DEPTH)
            else f"Kategori level {d + 1} apa yang paling menggambarkan `body`?"
        )
        levels[qid] = {"type": "choice", "instructions": instr, "criteria": crit}
    parent_qid = f"level_{depth - 1}"
    levels[f"level_{depth}"] = {
        "type": "choice",
        "depends_on": parent_qid,
        "instructions": (
            f"Kategori spesifik di bawah '{{{parent_qid}}}' yang paling "
            "menggambarkan percakapan di atas?"
        ),
        "branches": {
            parent: {leaf: None for leaf in kids}
            for parent, kids in flat[depth - 2].items()
        },
    }
    return {"hierarchical": True, "generated_from_paths": True, "levels": levels}


def convert(data):
    """Full pipeline: raw payload -> validated hierarchical config."""
    return hier_config_from_paths(parse_paths(data))
